- name: install python pip
  apt:
    update_cache: yes
    pkg: python3-pip
    state: present

- name: install python modules apt
  action: apt
          pkg={{ item }}
          state=present
          force=yes
  with_items:
    - python3-mysqldb
    - python3-passlib

- name: install python modules pip
  pip: 
    name: '{{ item }}'
    executable: pip3
  with_items: "{{ python.pip_modules }}" 
 