- name: check for spark
  stat:
    path: '{{spark.folder_spark}}/spark'
  register: spark_status

- name: download spark
  unarchive:
    src: '{{ spark.url }}'
    dest: '{{ spark.folder_spark }}'
    remote_src: yes
    mode: 0770
    owner: '{{ spark.user }}'
    group: '{{ spark.group }}'
  when: spark_status.stat.exists == False

- name: rename spark
  command: mv '{{spark.folder_spark}}/{{spark.file}}' '{{spark.folder_spark}}/spark'
  when: spark_status.stat.exists == False

- name: register spark variables
  lineinfile:
    dest: '/home/{{ spark.user }}/.bashrc'
    line: '{{item}}'
    insertafter: 'EOF'
    state: present
  with_items:
    - 'export PYSPARK_PYTHON=python3'
    - 'export PYSPARK_DRIVER_PYTHON=python3'
    - 'export SPARK_HOME={{spark.folder_spark}}/spark'
    - 'export PATH=$SPARK_HOME/bin:$PATH'
  when: spark_status.stat.exists == False
