- name: Create security group
  ec2_group:
    aws_access_key: "{{ ec2.access_key }}"
    aws_secret_key: "{{ ec2.secret_key }}"
    name: "{{ ec2.project_name }}_security_group"
    description: "{{ ec2.project_name }} security group"
    region: "{{ ec2.region }}"
    rules: "{{ ec2.security_rules }}"
  register: project_firewall

- name: Create an EC2 instance
  ec2:
    aws_access_key: "{{ ec2.access_key }}"
    aws_secret_key: "{{ ec2.secret_key }}"
    key_name: "{{ ec2.ssh_key }}"
    region: "{{ ec2.region }}"
    group_id: "{{ project_firewall.group_id }}"
    instance_type: "{{ ec2.instance_type }}"
    image: "{{ ec2.ami }}"
    wait: yes
    count_tag:
      Name: "{{ ec2.server_tag }}"
    instance_tags:
      Name: "{{ ec2.server_tag }}"
    exact_count: "{{ ec2.server_count }}"
    vpc_subnet_id: "{{ ec2.vpc_subnet_id }}"
    assign_public_ip: yes
  register: ec2i
  
- name: Add the newly created EC2 instance(s) to host group
  lineinfile:
    dest: "{{ ec2.hostpath }}"
    regexp: "{{ item.public_ip }}" 
    insertafter: "[{{ ec2.server_tag }}]" 
    line: "{{ item.public_ip }}"
    state: present
  with_items: "{{ ec2i['instances'] }}"

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: "{{ ec2i['instances'] }}"
